{% set version = "0.1.3" %}

package:
  name: pytest-mypy-testing
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-mypy-testing/pytest-mypy-testing-{{ version }}.tar.gz
  sha256: ad4c41232f5d5f6d54b85a34325612e29669d01eb4e173aaf1fb023fecc9e281

build:
  noarch: python
  script:
    # uses some strange, old fork of flit, but still has old school `setup.py`
    - {{ PYTHON }} -c "__import__('pathlib').Path('pyproject.toml').unlink()"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - mypy >=1.0
    - pytest >=7,<9
    - python >={{ python_min }}

test:
  source_files:
    - tests
    - mypy_tests
  imports:
    - pytest_mypy_testing
  commands:
    - pip check
    - mypy -p pytest_mypy_testing
    - coverage run --source=pytest_mypy_testing -m pytest tests mypy_tests --doctest-modules -p no:mypy-testing -k "not test_iter_comments"
    - coverage report --show-missing --skip-covered --fail-under=97
  requires:
    - pip
    - coverage
    - python {{ python_min }}

about:
  home: https://github.com/davidfritzsche/pytest-mypy-testing
  summary: Pytest plugin to check mypy output.
  license: Apache-2.0
  license_file:
    - LICENSES/MIT.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/Apache-2.0.txt

extra:
  recipe-maintainers:
    - bollwyvl
